### ISSUE TITLE
module import error

### ISSUE THREAD

**Issue by chenkenanalytic** [peisuke/MagicAnimateHandson#1]
Hi peisuke, 
First of all, thanks for your work.
Following is the error message while running 01_pose_estimation_for_magic_animate on colab.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-7-031c87de5ed4>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from apply_net import DumpAction
      2 import cv2
      3 import torch
      4 from detectron2.engine.defaults import DefaultPredictor
      5 from detectron2.data.detection_utils import read_image

5 frames
[/content/detectron2/projects/DensePose/densepose/data/video/video_keyframe_dataset.py](https://localhost:8080/#) in <module>
      6 import numpy as np
      7 from typing import Any, Callable, Dict, List, Optional, Union
----> 8 import av
      9 import torch
     10 from torch.utils.data.dataset import Dataset

ModuleNotFoundError: No module named 'av'

---------------------------------------------------------------------------

And I have noticed you have ` pip install av ` twice
but it shows:
Requirement already satisfied: av in /usr/local/lib/python3.10/dist-packages/av-11.0.0-py3.10-linux-x86_64.egg (11.0.0)

**Comment by peisuke** [comment]
I am aware of this issue, but I have been unable to resolve it directly.
Please re-run the installation cell (pip install av) and then re-run the cell to import DumpAction after you encounter the error. This should result in a successful import.

**Comment by chenkenanalytic** [comment]
It works, thanks!
